# Generated by Django 3.1.12 on 2021-06-13 02:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True)),
                ('summary', models.CharField(max_length=250)),
                ('thumnail', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2021, 6, 13, 2, 50, 48, 794519, tzinfo=utc))),
                ('update_at', models.DateTimeField(default=datetime.datetime(2021, 6, 13, 2, 50, 48, 794547, tzinfo=utc))),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blog',
                'ordering': ['-id'],
            },
        ),
    ]
