# Generated by Django 3.1.12 on 2021-06-13 02:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 2, 50, 55, 718733, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='update_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 13, 2, 50, 55, 718761, tzinfo=utc)),
        ),
    ]
